insert into Bestelling (Opmerking, Medewerker, Tafel, Rekening) values (null, 2, 3, 13);
insert into Bestelling (Opmerking, Medewerker, Tafel, Rekening) values (null, 4, 10, 15);
insert into Bestelling (Opmerking, Medewerker, Tafel, Rekening) values (null, 2, 7, 15);
insert into Bestelling (Opmerking, Medewerker, Tafel, Rekening) values (null, 3, 5, 8);
insert into Bestelling (Opmerking, Medewerker, Tafel, Rekening) values (null, 4, 5, 12);
insert into Bestelling (Opmerking, Medewerker, Tafel, Rekening) values ('Phasellus in felis. Donec semper sapien a libero. Nam dui.', 3, 6, 16);
insert into Bestelling (Opmerking, Medewerker, Tafel, Rekening) values ('Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 4, 6, 10);
insert into Bestelling (Opmerking, Medewerker, Tafel, Rekening) values ('Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 3, 5, 16);
insert into Bestelling (Opmerking, Medewerker, Tafel, Rekening) values (null, 2, 10, 11);
insert into Bestelling (Opmerking, Medewerker, Tafel, Rekening) values ('Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 3, 8, 12);
